// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Q1.Models;

public partial class Producer
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();
}