// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Q1.Models;

public partial class Star
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public bool? Male { get; set; }

    public DateOnly? Dob { get; set; }

    public string Description { get; set; }

    public string Nationality { get; set; }

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();
}