// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Q1.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateOnly? LaunchDate { get; set; }

    public string Description { get; set; }

    public string Material { get; set; }

    public int? ManufacturerId { get; set; }

    public int? DesignerId { get; set; }

    public virtual Designer Designer { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }

    public virtual ICollection<Reviewer> Reviewers { get; set; } = new List<Reviewer>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}