// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Q1.Models;

public partial class Book
{
    public int Id { get; set; }

    public string Title { get; set; }

    public DateOnly? PublishDate { get; set; }

    public string Description { get; set; }

    public string Language { get; set; }

    public int? PublisherId { get; set; }

    public int? AuthorId { get; set; }

    public virtual Author Author { get; set; }

    public virtual Publisher Publisher { get; set; }

    public virtual ICollection<Genre> Genres { get; set; } = new List<Genre>();

    public virtual ICollection<Translator> Translators { get; set; } = new List<Translator>();
}